# Generated by Django 3.2 on 2022-12-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='impresora',
            name='toner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.toner'),
        ),
    ]
