# Generated by Django 3.2 on 2022-12-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20221219_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='toner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro.toner'),
            preserve_default=False,
        ),
    ]
