# Generated by Django 4.1.3 on 2022-12-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_impresora_toner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.impresora')),
            ],
        ),
    ]
