# Generated by Django 4.1.3 on 2022-12-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_toner_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
